### ISSUE TITLE
RFE: Add option to ignore files

### ISSUE THREAD

**Issue by tradej** [devassistant/dap-dap#1]
Currently, `da twk dap pack` packs all files within the file structure, even temporary files like *.swp and the like. It would be nice to have an option to ignore these kind of files. The best place where to take the information which files should be ignored is IMHO `.gitignore`.

**Comment by bkabrda** [comment]
- The documentation in the side branch mentions `.gapingnore` several times. That is a typo and should be `.dapignore`, right?
- I'm ok with the implementation, assuming it works, but wouldn't it be more readable to create a custom command runner for that, load it and run it? Some people may want to reuse that sometime and they could depend on dap-dap and reuse that command runner instead C&P the crazy bash snippet :)
