### ISSUE TITLE
RFE: Ability to name the repo and Assistant differently

### ISSUE THREAD

**Issue by tradej** [devassistant/dap-dap#2]
When creating a DAP repo on GitHub, the developer usually wants to have a name like `dap-foobar`. However, the Assistant's name should be only `foobar`. It would be nice to e. g. add a prefix `dap-` to the name unless the user specifies a e. g. `--verbatim` option, in which case a repo with an identical name to the Assistant name is created.

**Comment by bkabrda** [comment]
Can you please get this packaged and released to DAPI?

**Comment by hroncok** [comment]
@bkabrda Somebody already created a milestone (I cannot see who), so I've added every pending issue to it and will release this (maybe as beta) once all the issues are closed.

See https://github.com/devassistant/dap-dap/milestones/0.1
