### ISSUE TITLE
Terms of Use link when uploading

### ISSUE THREAD

**Issue by hroncok** [devassistant/dap-dap#5]
It would be safer if we provide Terms of Use link to the user when uploading a DAP.

If we just log.info the link, user cannot stop the upload in time when (s)he reads the terms.

If we prompt for confirmation (e.g. for the first time only), we will break scripted scenarios, such as Travis. So we might introduce `--i-agree-with-terms` option that would suppress the interactive confirmation.

**Comment by hroncok** [comment]
Any thoughts abut the correct approach here?

**Comment by tradej** [comment]
I'm in favour of asking the first time, and having the `--agree-with-terms` flag for automated scenarios.

However, asking only the first time requires storing the information about the initital agreement somwhere. To my knowledge, DA doesn't provide a straightforward way of storing configuration to Assistants, so I think we're facing a choice between essentially these two options:
* Hardcode a location of a config file into the DAP Assistant. The file's existence/contents indicate the user agreed to the DAPI terms.
* Provide a uniform way of storing config to Assistants in DA and use that for storing the fact.

**Comment by hroncok** [comment]
In this case, I'm already storing the token (in git config).

On the other way I would say user has to agree all times (s)he uploads, so I guess we don't even need to remember that. Similar way DNF Copr plugin always shows a warning. Users who are annoyed can pass `--agree-with-terms`.
